name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libpng-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make -j3
